msgid ""
msgstr "Project-Id-Version: pyload\n"
"Report-Msgid-Bugs-To: 'bugs@pyload.org'\n"
"POT-Creation-Date: 2014-04-08 15:01+0200\n"
"PO-Revision-Date: 2014-04-09 05:39-0400\n"
"Last-Translator: pyloadTeam <team@pyload.org>\n"
"Language-Team: Hungarian\n"
"Language: hu_HU\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: crowdin.net\n"

#: pyload/Core.py:182
msgid "Received Quit signal"
msgstr "Leállítási jel érkezett"

#: pyload/Core.py:303
#, python-format
msgid "pyLoad already running with pid %s"
msgstr "a pyLoad már fut az alábbi pid számmal: %s"

#: pyload/Core.py:317
#, python-format
msgid "Failed changing group: %s"
msgstr "Sikertelen csoport váltás: %s"

#: pyload/Core.py:327
#, python-format
msgid "Failed changing user: %s"
msgstr "Sikertelen felhasználó váltás: %s"

#: pyload/Core.py:329
msgid "folder for logs"
msgstr "könyvtár a naplóknak"

#: pyload/Core.py:340
msgid "Starting"
msgstr "Indítás"

#: pyload/Core.py:341
#, python-format
msgid "Using home directory: %s"
msgstr "Főkönyvtár használata: %s"

#: pyload/Core.py:350
msgid "pycrypto to decode container files"
msgstr "pycrypto a konténer fájlok dekódolásához"

#: pyload/Core.py:353
msgid "folder for temporary files"
msgstr "könyvtár az átmeneti fájloknak"

#: pyload/Core.py:358
msgid "folder for downloads"
msgstr "könyvtár a letöltéseknek"

#: pyload/Core.py:361
msgid "OpenSSL for secure connection"
msgstr "OpenSSL a biztonságos kapcsolathoz"

#: pyload/Core.py:365
msgid "Moving old user config to DB"
msgstr ""

#: pyload/Core.py:368
msgid "Please check your logindata with ./pyload.py -u"
msgstr "Ellenőrizd a belépési adataid a következő paranccsal: ./pyload.py -u"

#: pyload/Core.py:371
msgid "All links removed"
msgstr "Minden link törölve"

#: pyload/Core.py:402
#, python-format
msgid "Downloadtime: %s"
msgstr "Letöltési idő: %s"

#: pyload/Core.py:412
#, python-format
msgid "Free space: %s"
msgstr "Szabad hely: %s"

#: pyload/Core.py:432
msgid "Activating Accounts..."
msgstr "Hozzáférések aktiválása..."

#: pyload/Core.py:438
msgid "Activating Plugins..."
msgstr "Bővítmények aktiválása..."

#: pyload/Core.py:441
msgid "pyLoad is up and running"
msgstr "pyLoad fut"

#: pyload/Core.py:460
msgid "restarting pyLoad"
msgstr "pyLoad újraindítása"

#: pyload/Core.py:464
msgid "pyLoad quits"
msgstr "pyLoad kilép"

#: pyload/Core.py:521
#, python-format
msgid "Install %s"
msgstr "Telepítés %s"

#: pyload/Core.py:557
#, python-format
msgid "could not find %(desc)s: %(name)s"
msgstr ""

#: pyload/Core.py:559
#, python-format
msgid "could not create %(desc)s: %(name)s"
msgstr ""

#: pyload/Core.py:580
msgid "shutting down..."
msgstr "leállítás..."

#: pyload/Core.py:597
msgid "error while shutting down"
msgstr "hiba leállítás közben"

#: pyload/Core.py:661
msgid "killed pyLoad from Terminal"
msgstr "pyLoad kilőve konzolról"

#: pyload/database/DatabaseBackend.py:174
msgid "Filedatabase was deleted due to incompatible version."
msgstr ""

#: pyload/database/DatabaseBackend.py:189
msgid "Filedatabase could NOT be converted."
msgstr ""

#: pyload/database/DatabaseBackend.py:198
msgid "Database was converted from v2 to v3."
msgstr ""

#: pyload/database/DatabaseBackend.py:206
msgid "Database was converted from v3 to v4."
msgstr ""

#: pyload/database/DatabaseBackend.py:252
msgid "Converting old Django DB"
msgstr ""

#: pyload/database/FileDatabase.py:45
msgid "finished"
msgstr "befejezett"

#: pyload/database/FileDatabase.py:45
msgid "offline"
msgstr ""

#: pyload/database/FileDatabase.py:45
msgid "online"
msgstr ""

#: pyload/database/FileDatabase.py:45
msgid "queued"
msgstr "várólistán"

#: pyload/database/FileDatabase.py:45
msgid "skipped"
msgstr "átugorva"

#: pyload/database/FileDatabase.py:45
msgid "waiting"
msgstr "várakozás"

#: pyload/database/FileDatabase.py:45
msgid "temp. offline"
msgstr "átmenetileg offline"

#: pyload/database/FileDatabase.py:45
msgid "starting"
msgstr "indítás"

#: pyload/database/FileDatabase.py:45
msgid "failed"
msgstr "sikertelen"

#: pyload/database/FileDatabase.py:45
msgid "aborted"
msgstr "megszakított"

#: pyload/database/FileDatabase.py:45
msgid "decrypting"
msgstr "dekódolás"

#: pyload/database/FileDatabase.py:45
msgid "custom"
msgstr "egyéni"

#: pyload/database/FileDatabase.py:45
msgid "downloading"
msgstr "letöltés"

#: pyload/database/FileDatabase.py:45
msgid "processing"
msgstr "feldolgozás alatt"

#: pyload/database/FileDatabase.py:45
msgid "unknown"
msgstr "ismeretlen"

#: pyload/database/FileDatabase.py:531 pyload/plugins/addon/IRCInterface.py:74
#: pyload/plugins/addon/XMPPInterface.py:83
#, python-format
msgid "Package finished: %s"
msgstr "Kész csomag: %s"

#: pyload/remote/ThriftBackend.py:39
msgid "Using SSL ThriftBackend"
msgstr "SSL ThriftBackend használata"

#: pyload/manager/RemoteManager.py:35
#, python-format
msgid "Remote backend error: %s"
msgstr "Távoli hiba: %s"

#: pyload/manager/RemoteManager.py:82
#, python-format
msgid "Starting %(name)s: %(addr)s:%(port)s"
msgstr "Indítás: %(name)s: %(addr)s:%(port)s"

#: pyload/manager/RemoteManager.py:84
#, python-format
msgid "Failed loading backend %(name)s | %(error)s"
msgstr "Backend betöltése sikertelen: %(name)s | %(error)s"

#: pyload/webui/app/json.py:57
#, python-format
msgid "waiting %s"
msgstr "várakozás %s"

#: pyload/thread/ServerThread.py:35
msgid "SSL certificates not found."
msgstr "SSL tanúsítvány nem található."

#: pyload/thread/ServerThread.py:39
#, python-format
msgid "Sorry, we dropped support for starting %s directly within pyLoad"
msgstr ""

#: pyload/thread/ServerThread.py:40
msgid "You can use the threaded server which offers good performance and ssl,"
msgstr ""

#: pyload/thread/ServerThread.py:41
#, python-format
msgid "of course you can still use your existing %s with pyLoads fastcgi server"
msgstr ""

#: pyload/thread/ServerThread.py:42
msgid "sample configs are located in the tools/webserver directory"
msgstr ""

#: pyload/thread/ServerThread.py:49
#, python-format
msgid "Can't use %(server)s, python-flup is not installed!"
msgstr ""

#: pyload/thread/ServerThread.py:56
#, python-format
msgid "Error importing lightweight server: %s"
msgstr ""

#: pyload/thread/ServerThread.py:57
msgid "You need to download and compile bjoern, https://github.com/jonashaag/bjoern"
msgstr ""

#: pyload/thread/ServerThread.py:58
msgid "Copy the boern.so to pyload/lib folder or use Setup.py install"
msgstr ""

#: pyload/thread/ServerThread.py:59
msgid "Of course you need to be familiar with linux and know how to compile software"
msgstr ""

#: pyload/thread/ServerThread.py:63
msgid "Server set to threaded, due to known performance problems on windows."
msgstr ""

#: pyload/thread/ServerThread.py:80 pyload/thread/ServerThread.py:103
msgid "This server offers no SSL, please consider using threaded instead"
msgstr "Ez a szerver nem támogatja az SSL-t, kérlek használj helyette másikat"

#: pyload/thread/ServerThread.py:82
#, python-format
msgid "Starting builtin webserver: %(host)s:%(port)d"
msgstr ""

#: pyload/thread/ServerThread.py:87
#, python-format
msgid "Starting threaded SSL webserver: %(host)s:%(port)d"
msgstr ""

#: pyload/thread/ServerThread.py:91
#, python-format
msgid "Starting threaded webserver: %(host)s:%(port)d"
msgstr ""

#: pyload/thread/ServerThread.py:97
#, python-format
msgid "Starting fastcgi server: %(host)s:%(port)d"
msgstr ""

#: pyload/thread/ServerThread.py:105
#, python-format
msgid "Starting lightweight webserver (bjoern): %(host)s:%(port)d"
msgstr ""

#: pyload/webui/app/pyload.py:125
msgid "You dont have permission to access this page."
msgstr "Nincs jogosultságod a lap megtekintéséhez."

#: pyload/webui/app/pyload.py:193
msgid "Download directory not found."
msgstr "Letöltési könyvtár nem található."

#: pyload/webui/app/pyload.py:260 pyload/webui/app/pyload.py:267
msgid "unlimited"
msgstr "végtelen"

#: pyload/webui/app/pyload.py:262 pyload/webui/app/pyload.py:269
msgid "not available"
msgstr "nem elérhető"

#: pyload/webui/app/pyload.py:508
msgid "Run pyload.py -s to access the setup."
msgstr "A beállításhoz futtasd: pyload.py -s."

#: pyload/network/HTTPDownload.py:245
#, python-format
msgid "Download chunks failed, fallback to single connection | %s"
msgstr "Darabokban letöltés sikertelen, visszatérés egyszeri kapcsolatra | %s"

#: pyload/thread/PluginThread.py:183
#, python-format
msgid "Download starts: %s"
msgstr "Letöltés elindítva: %s"

#: pyload/thread/PluginThread.py:189
#, python-format
msgid "Download finished: %s"
msgstr "Letöltés befejezve: %s"

#: pyload/thread/PluginThread.py:194 pyload/thread/PluginThread.py:365
#, python-format
msgid "Plugin %s is missing a function."
msgstr "A %s bővítményből hiányzik egy funkció."

#: pyload/thread/PluginThread.py:202 pyload/thread/PluginThread.py:265
#: pyload/thread/PluginThread.py:382
#, python-format
msgid "Download aborted: %s"
msgstr "Letöltés megszakítva: %s"

#: pyload/thread/PluginThread.py:222
#, python-format
msgid "Download restarted: %(name)s | %(msg)s"
msgstr "Letöltés újraindítva: %(name)s | %(msg)s"

#: pyload/thread/PluginThread.py:231 pyload/thread/PluginThread.py:373
#, python-format
msgid "Download is offline: %s"
msgstr "A letöltés offline: %s"

#: pyload/thread/PluginThread.py:234
#, python-format
msgid "Download is temporary offline: %s"
msgstr "A letöltés átmenetileg offline: %s"

#: pyload/thread/PluginThread.py:237 pyload/thread/PluginThread.py:304
#, python-format
msgid "Download failed: %(name)s | %(msg)s"
msgstr "A letöltés sikertelen: %(name)s | %(msg)s"

#: pyload/thread/PluginThread.py:254
msgid "Couldn't connect to host or connection reset, waiting 1 minute and retry."
msgstr "Nem sikerült csatlakozni a címhez, újrapróbálás 1 perc múlva."

#: pyload/thread/PluginThread.py:290
#, python-format
msgid "Download skipped: %(name)s due to %(plugin)s"
msgstr "Letöltés átugorva: %(name)s - %(plugin)s"

#: pyload/thread/PluginThread.py:361
#, python-format
msgid "Decrypting starts: %s"
msgstr "Dekódolás elkezdve: %s"

#: pyload/thread/PluginThread.py:376 pyload/thread/PluginThread.py:394
#, python-format
msgid "Decrypting failed: %(name)s | %(msg)s"
msgstr "Dekódolás sikertelen: %(name)s | %(msg)s"

#: pyload/thread/PluginThread.py:388
#, python-format
msgid "Retrying %s"
msgstr "Újra próbálkozás %s"

#: pyload/thread/PluginThread.py:635
#, python-format
msgid "Info Fetching for %(name)s failed | %(err)s"
msgstr "%(name)s információinak lekérése sikertelen | %(err)s"

#: pyload/manager/AddonManager.py:90 pyload/plugins/Addon.py:102
#, python-format
msgid "Error executing addon: %s"
msgstr ""

#: pyload/manager/AddonManager.py:140
#, python-format
msgid "Failed activating %(name)s"
msgstr "Sikertelen aktiválás: %(name)s"

#: pyload/manager/AddonManager.py:144
#, python-format
msgid "Activated plugins: %s"
msgstr ""

#: pyload/manager/AddonManager.py:145
#, python-format
msgid "Deactivate plugins: %s"
msgstr ""

#: pyload/manager/ThreadManager.py:137
#, python-format
msgid "Reconnect Failed: %s"
msgstr "Újracsatlakozás sikertelen: %s"

#: pyload/manager/ThreadManager.py:176
msgid "Reconnect script not found!"
msgstr "Újracsatlakozó script nem található!"

#: pyload/manager/ThreadManager.py:182
msgid "Starting reconnect"
msgstr "Újracsatlakozás indítása"

#: pyload/manager/ThreadManager.py:196
msgid "Failed executing reconnect script!"
msgstr "Az újracsatlakozó scriptet nem sikerült futtatni!"

#: pyload/manager/ThreadManager.py:208
#, python-format
msgid "Reconnected, new IP: %s"
msgstr "Újracsatlakozva, új IP: %s"

#: pyload/manager/ThreadManager.py:288
msgid "Not enough space left on device"
msgstr "Nincs elég hely az eszközön"

#: pyload/plugins/Account.py:85 pyload/plugins/Account.py:91
#, python-format
msgid "Could not login with account %(user)s | %(msg)s"
msgstr "Nem sikerült bejelentkezni: %(user)s | %(msg)s"

#: pyload/plugins/Account.py:86
msgid "Wrong Password"
msgstr "Hibás jelszó"

#: pyload/plugins/Account.py:240
#, python-format
msgid "Your Time %s has wrong format, use: 1:22-3:44"
msgstr ""

#: pyload/plugins/Account.py:266
#, python-format
msgid "Account %s has not enough traffic, checking again in 30min"
msgstr "%s hozzáférésen nincs elég adatforgalom, újra próbálás: 30 perc"

#: pyload/plugins/Account.py:273
#, python-format
msgid "Account %s is expired, checking again in 1h"
msgstr "%s hozzáférés lejárt, újra próbálás: 1 óra"

#: pyload/plugins/crypter/SerienjunkiesOrg.py:128
msgid "Downloadlimit reached"
msgstr "A letöltési korlát elérve"

#: pyload/manager/PluginManager.py:153
#, python-format
msgid "%s has a invalid pattern."
msgstr ""

#: pyload/manager/PluginManager.py:272
#, python-format
msgid "Error importing %(name)s: %(msg)s"
msgstr "Hiba a(z) %(name)s betöltése közben: %(msg)s"

#: pyload/plugins/internal/MultiHoster.py:133
msgid "No Hoster loaded"
msgstr "Nincs szolgáltató betöltve"

#: pyload/plugins/account/BitshareCom.py:37
msgid "Activate direct Download in your Bitshare Account"
msgstr "Közvetlen letöltés aktiválása a Bitshare hozzáférésen"

#: pyload/plugins/container/LinkList.py:65
msgid "LinkList could not be cleared."
msgstr ""

#: pyload/manager/AccountManager.py:88
msgid "Account settings deleted, due to new config format."
msgstr ""

#: pyload/plugins/hoster/BasePlugin.py:65
msgid "Authorization required (username:password)"
msgstr "Azonosítás szükséges (felhasználónév:jelszó)"

#: pyload/plugins/hoster/SimplydebridCom.py:25
#: pyload/plugins/hoster/RealdebridCom.py:41
#: pyload/plugins/hoster/FreeWayMe.py:38 pyload/plugins/hoster/ZeveraCom.py:22
#: pyload/plugins/hoster/UnrestrictLi.py:53
#: pyload/plugins/hoster/Premium4Me.py:28 pyload/plugins/hoster/FastixRu.py:36
#: pyload/plugins/hoster/AlldebridCom.py:38
#: pyload/plugins/hoster/DebridItaliaCom.py:40
#: pyload/plugins/hoster/RPNetBiz.py:26
#: pyload/plugins/hoster/MultiDebridCom.py:41
#: pyload/plugins/hoster/ReloadCc.py:24 pyload/plugins/hoster/RehostTo.py:26
#: pyload/plugins/hoster/PremiumizeMe.py:22
#: pyload/plugins/addon/RPNetBiz.py:43
#, python-format
msgid "Please enter your %s account or deactivate this plugin"
msgstr "Add meg a(z) %s hozzáférés adatait, vagy deaktiváld ezt a beépülőt"

#: pyload/plugins/hoster/FilesMailRu.py:99
#, python-format
msgid "There was HTML Code in the Downloaded File (%s)...redirect error? The Download will be restarted."
msgstr "HTML kód van a letöltött fájlban (%s). Lehet, hogy átirányítási hiba, a letöltés újra lesz indítva."

#: pyload/plugins/hoster/NetloadIn.py:146
#: pyload/plugins/hoster/NetloadIn.py:170
msgid "File temporarily not available"
msgstr "Állomány átmenetileg nem elérhető"

#: pyload/plugins/hoster/NetloadIn.py:183
#, python-format
msgid "Netload: waiting between downloads %d s."
msgstr "Netload: letöltések közti várakozás %d mp."

#: pyload/plugins/hoster/NetloadIn.py:214
#, python-format
msgid "Netload: waiting for captcha %d s."
msgstr "Netload: captcha-ra várakozás %d mp."

#: pyload/plugins/hoster/NetloadIn.py:252
msgid "Downloaded File was empty"
msgstr "A letöltött fájl üres"

#: pyload/plugins/hoster/UploadedTo.py:129
msgid "API key invalid"
msgstr "Érvénytelen API kulcs"

#: pyload/plugins/hoster/UploadedTo.py:153
#, python-format
msgid "%s: Not enough traffic left"
msgstr "%s: Nincs elég adatforgalom hátra"

#: pyload/plugins/hoster/UploadedTo.py:156
msgid "Traffic exceeded"
msgstr "Adatforgalom túllépve"

#: pyload/plugins/hoster/RapidshareCom.py:100
msgid "Rapidshare: Traffic Share (direct download)"
msgstr "Rapidshare: Adatforgalom  megosztás (közvetlen letöltés)"

#: pyload/plugins/hoster/RapidshareCom.py:127
#: pyload/plugins/hoster/RapidshareCom.py:194
msgid "Already downloading from this ip address, waiting 60 seconds"
msgstr "Már van folyamatban letöltés erről az IP-ről, várakozás: 60mp"

#: pyload/plugins/hoster/RapidshareCom.py:131
msgid "Invalid Auth Code, download will be restarted"
msgstr "Hibás Auth kód, a letöltés újraindítása"

#: pyload/plugins/hoster/RapidshareCom.py:199
msgid "RapidShareCom: No free slots"
msgstr "RapidShareCom: Nincs ingyenes hely"

#: pyload/plugins/hoster/RapidshareCom.py:202
msgid "You need a premium account for this file"
msgstr "Ehhez a fájlhoz prémium hozzáférés szükséges"

#: pyload/plugins/hoster/RapidshareCom.py:204
msgid "Filename reported invalid"
msgstr "Hibás fájlnév"

#: pyload/plugins/hoster/FileserveCom.py:99
msgid "Parallel download error, now waiting 60s."
msgstr "Többszálas letöltés hiba, várakozás: 60s."

#: pyload/plugins/hoster/FileserveCom.py:215
msgid "Not logged in."
msgstr "Nem vagy bejelentkezve."

#: pyload/plugins/hoster/MegaNz.py:56
msgid "Decryption failed"
msgstr "Sikertelen dekódolás"

#: pyload/plugins/hoster/MegaNz.py:106
msgid "No file key provided in the URL"
msgstr "Nincs fájl kulcs az URL-ben"

#: pyload/plugins/hoster/MegaNz.py:118
msgid "Error code:"
msgstr "Hibakód:"

#: pyload/plugins/Container.py:68
msgid "File not exists."
msgstr ""

#: pyload/plugins/addon/UpdateManager.py:74
msgid "*** Plugins have been updated, please restart pyLoad ***"
msgstr "*** Bővítmények frissítve, indítsd újra a pyLoad-ot ***"

#: pyload/plugins/addon/UpdateManager.py:76
msgid "Plugins updated and reloaded"
msgstr "Bővítmények frissítve és betöltve"

#: pyload/plugins/addon/UpdateManager.py:79
msgid "No plugin updates available"
msgstr "Nincs bővítmény frissítés"

#: pyload/plugins/addon/UpdateManager.py:96
msgid "No Updates for pyLoad"
msgstr "Nincs új pyLoad verzió"

#: pyload/plugins/addon/UpdateManager.py:100
#, python-format
msgid "***  New pyLoad Version %s available  ***"
msgstr "***  Új pyLoad verzió elérhető: %s  ***"

#: pyload/plugins/addon/UpdateManager.py:101
msgid "***  Get it here: http://pyload.org/download  ***"
msgstr "***  Letöltés: http://pyload.org/download  ***"

#: pyload/plugins/addon/UpdateManager.py:104
msgid "Not able to connect server for updates"
msgstr "Nem sikerült a szerverhez csatlakozni a frissítésekért"

#: pyload/plugins/addon/UpdateManager.py:148
#, python-format
msgid "New version of %(type)s|%(name)s : %(version).2f"
msgstr "Új verzió: %(type)s|%(name)s : %(version).2f"

#: pyload/plugins/addon/UpdateManager.py:157
#: pyload/plugins/addon/UpdateManager.py:162
#, python-format
msgid "Error when updating %s"
msgstr "Hiba frissítés közben %s"

#: pyload/plugins/addon/UpdateManager.py:162
msgid "Version mismatch"
msgstr "verzió ütközés"

#: pyload/plugins/addon/IRCInterface.py:82
#, python-format
msgid "Download finished: %(name)s @ %(plugin)s "
msgstr "Letöltés befejezve: %(name)s @ %(plugin)s "

#: pyload/plugins/addon/IRCInterface.py:95
#, python-format
msgid "New Captcha Request: %s"
msgstr "Új captcha kérés: %s"

#: pyload/plugins/addon/IRCInterface.py:96
#, python-format
msgid "Answer with 'c %s text on the captcha'"
msgstr "Válaszolj ezzel: 'c %s szöveg a captcha-n'"

#: pyload/plugins/addon/Premium4Me.py:29
msgid "Please add your premium.to account first and restart pyLoad"
msgstr "Először adj meg rehost.to hozzáférést majd indítsd újra a pyLoad-ot"

#: pyload/plugins/addon/HotFolder.py:82
#, python-format
msgid "Added %s from HotFolder"
msgstr "%s HotFolder-ből hozzáadva"

#: pyload/plugins/addon/ExtractArchive.py:95
#, python-format
msgid "No %s installed"
msgstr "Nincs %s telepítve"

#: pyload/plugins/addon/ExtractArchive.py:97
#: pyload/plugins/addon/ExtractArchive.py:102
#, python-format
msgid "Could not activate %s"
msgstr "Nem sikerült aktiválni: %s"

#: pyload/plugins/addon/ExtractArchive.py:107
msgid "Activated"
msgstr "Aktivált"

#: pyload/plugins/addon/ExtractArchive.py:109
msgid "No Extract plugins activated"
msgstr "Nincs kicsomagoló bővítmény aktiválva"

#: pyload/plugins/addon/ExtractArchive.py:121
#, python-format
msgid "Package %s queued for later extracting"
msgstr "%s csomag a várólistán későbbi kitömörítésre"

#: pyload/plugins/addon/ExtractArchive.py:144
#, python-format
msgid "Check package %s"
msgstr "Csomag ellenőrzése: %s"

#: pyload/plugins/addon/ExtractArchive.py:185
#, python-format
msgid "Extract to %s"
msgstr "Kicsomagolás: %s"

#: pyload/plugins/addon/ExtractArchive.py:200
msgid "No files found to extract"
msgstr "Nincs kitömöríthető fájl"

#: pyload/plugins/addon/ExtractArchive.py:207
msgid "extracting"
msgstr "kicsomagolás"

#: pyload/plugins/addon/ExtractArchive.py:218
msgid "Password protected"
msgstr "Jelszóval védett"

#: pyload/plugins/addon/ExtractArchive.py:239
msgid "Wrong password"
msgstr "Hibás jelszó"

#: pyload/plugins/addon/ExtractArchive.py:247
#, python-format
msgid "Deleting %s files"
msgstr "%s fájl törlése"

#: pyload/plugins/addon/ExtractArchive.py:254
msgid "Extracting finished"
msgstr "Kicsomagolás kész"

#: pyload/plugins/addon/ExtractArchive.py:260
msgid "Archive Error"
msgstr "Tömörített állomány hiba"

#: pyload/plugins/addon/ExtractArchive.py:262
msgid "CRC Mismatch"
msgstr "CRC hiba"

#: pyload/plugins/addon/ExtractArchive.py:266
msgid "Unknown Error"
msgstr "Ismeretlen hiba"

#: pyload/plugins/addon/ExtractArchive.py:318
msgid "Setting User and Group failed"
msgstr "Felhasználó és csoport beállítás sikertelen"

#: pyload/plugins/addon/ClickAndLoad.py:75
msgid "Click'N'Load: Port 9666 already in use"
msgstr "Click'N'Load: A 9666 port használatban van"

#: pyload/plugins/addon/CaptchaTrader.py:69
#: pyload/plugins/addon/Captcha9kw.py:59
#: pyload/plugins/addon/ExpertDecoders.py:50
#, python-format
msgid "%s credits left"
msgstr "%s kredit maradt"

#: pyload/plugins/addon/CaptchaTrader.py:117
msgid "Could not send response."
msgstr "Nem sikerült választ küldeni."

#: pyload/plugins/addon/CaptchaTrader.py:135
msgid "Your CaptchaTrader Account has not enough credits"
msgstr "A CaptchaTrader hozzáférésen nincs elég credit"

#: pyload/plugins/addon/LinkdecrypterCom.py:43
msgid "Crypter list not found"
msgstr "Crypter lista nem található"

#: pyload/plugins/addon/LinkdecrypterCom.py:57
msgid "Crypter list is empty"
msgstr "Crypter lista üres"

#: pyload/plugins/addon/XMPPInterface.py:91
#, python-format
msgid "Download finished: %(name)s @ %(plugin)s"
msgstr "Letöltés befejezve: %(name)s @ %(plugin)s"

#: pyload/plugins/addon/Captcha9kw.py:93
#, python-format
msgid "New CaptchaID from upload: %s : %s"
msgstr "Új CaptchaID a feltöltésből:  %s : %s"

#: pyload/plugins/addon/Captcha9kw.py:129
msgid "Your Captcha 9kw.eu Account has not enough credits"
msgstr "A Captcha 9kw.eu hozzáférésen nincs elég credit"

#: pyload/plugins/addon/ExternalScripts.py:54
#, python-format
msgid "Installed scripts for %s: "
msgstr "Scriptek telepítve - %s: "

#: pyload/plugins/addon/ExternalScripts.py:69
msgid "Script not executable:"
msgstr "Script nem futtatható:"

#: pyload/plugins/addon/ExternalScripts.py:80
#, python-format
msgid "Error in %(script)s: %(error)s"
msgstr "Hiba: %(script)s: %(error)s"

#: pyload/plugins/addon/ExpertDecoders.py:95
msgid "Your ExpertDecoders Account has not enough credits"
msgstr "Az ExpertDecoders hozzáférésen nincs elég credit"

#: pyload/plugins/addon/RehostTo.py:32
msgid "Please add your rehost.to account first and restart pyLoad"
msgstr "Először adj meg rehost.to hozzáférést majd indítsd újra a pyLoad-ot."

#: pyload/plugins/addon/PremiumizeMe.py:48
msgid "Please add a valid premiumize.me account first and restart pyLoad."
msgstr "Először adj meg premiumize.me hozzáférést majd indítsd újra a pyLoad-ot."

#: pyload/plugins/addon/CaptchaBrotherhood.py:69
#, python-format
msgid "%d credits left"
msgstr "%d kredit maradt"

#: pyload/plugins/Base.py:389
msgid "Pil and tesseract not installed and no Client connected for captcha decrypting"
msgstr "Captcha megfejtéshez nincs kliens csatlakozva és nincs telepítve Pil vagy tesseract"

#: pyload/plugins/Base.py:393
msgid "No captcha result obtained in appropiate time by any of the plugins."
msgstr ""

#: pyload/plugins/Base.py:498 pyload/plugins/Base.py:532
#, python-format
msgid "Setting User and Group failed: %s"
msgstr "Felhasználó és csoport beállítás sikertelen: %s"

#: pyload/manager/CaptchaManager.py:78
msgid "No Client connected for captcha decrypting"
msgstr ""

#: pyload/api/__init__.py:330
#, python-format
msgid "Added package %(name)s containing %(count)d links"
msgstr ""

#: pyload/api/__init__.py:593
#, python-format
msgid "Added %(count)d links to package #%(package)d "
msgstr ""

#: pyload/manager/JsEngine.py:156
msgid "No js engine detected, please install either Spidermonkey, ossp-js, pyv8 or rhino"
msgstr ""

