msgid ""
msgstr "Project-Id-Version: pyload\n"
"Report-Msgid-Bugs-To: 'bugs@pyload.org'\n"
"POT-Creation-Date: 2014-04-08 15:01+0200\n"
"PO-Revision-Date: 2014-04-09 05:39-0400\n"
"Last-Translator: pyloadTeam <team@pyload.org>\n"
"Language-Team: Portuguese, Brazilian\n"
"Language: pt_BR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: crowdin.net\n"

#: pyload.py:182
msgid "Received Quit signal"
msgstr "sinal de Sair recebido"

#: pyload.py:303
#, python-format
msgid "pyLoad already running with pid %s"
msgstr "pyLoad já está rodando com pid %s"

#: pyload.py:317
#, python-format
msgid "Failed changing group: %s"
msgstr "Falha ao trocar grupo: %s"

#: pyload.py:327
#, python-format
msgid "Failed changing user: %s"
msgstr "Falha ao trocar de usuario: %s"

#: pyload.py:329
msgid "folder for logs"
msgstr ""

#: pyload.py:340
msgid "Starting"
msgstr "Iniciando"

#: pyload.py:341
#, python-format
msgid "Using home directory: %s"
msgstr "Usando diretório: %s"

#: pyload.py:350
msgid "pycrypto to decode container files"
msgstr ""

#: pyload.py:353
msgid "folder for temporary files"
msgstr ""

#: pyload.py:358
msgid "folder for downloads"
msgstr ""

#: pyload.py:361
msgid "OpenSSL for secure connection"
msgstr ""

#: pyload.py:365
msgid "Moving old user config to DB"
msgstr ""

#: pyload.py:368
msgid "Please check your logindata with ./pyload.py -u"
msgstr ""

#: pyload.py:371
msgid "All links removed"
msgstr "Todos os links foram removidos"

#: pyload.py:402
#, python-format
msgid "Downloadtime: %s"
msgstr ""

#: pyload.py:412
#, python-format
msgid "Free space: %s"
msgstr "Espaço livre: %s"

#: pyload.py:432
msgid "Activating Accounts..."
msgstr "Ativando contas..."

#: pyload.py:438
msgid "Activating Plugins..."
msgstr ""

#: pyload.py:441
msgid "pyLoad is up and running"
msgstr "pyLoad está rodando"

#: pyload.py:460
msgid "restarting pyLoad"
msgstr "reiniciando pyLoad"

#: pyload.py:464
msgid "pyLoad quits"
msgstr "pyLoad fechou"

#: pyload.py:521
#, python-format
msgid "Install %s"
msgstr ""

#: pyload.py:557
#, python-format
msgid "could not find %(desc)s: %(name)s"
msgstr ""

#: pyload.py:559
#, python-format
msgid "could not create %(desc)s: %(name)s"
msgstr ""

#: pyload.py:580
msgid "shutting down..."
msgstr "desligando..."

#: pyload.py:597
msgid "error while shutting down"
msgstr "erro durante desligamento"

#: pyload.py:661
msgid "killed pyLoad from Terminal"
msgstr ""

#: module/database/DatabaseBackend.py:174
msgid "Filedatabase was deleted due to incompatible version."
msgstr ""

#: module/database/DatabaseBackend.py:189
msgid "Filedatabase could NOT be converted."
msgstr ""

#: module/database/DatabaseBackend.py:198
msgid "Database was converted from v2 to v3."
msgstr ""

#: module/database/DatabaseBackend.py:206
msgid "Database was converted from v3 to v4."
msgstr ""

#: module/database/DatabaseBackend.py:252
msgid "Converting old Django DB"
msgstr ""

#: module/database/FileDatabase.py:45
msgid "finished"
msgstr "Terminado"

#: module/database/FileDatabase.py:45
msgid "offline"
msgstr "Offline"

#: module/database/FileDatabase.py:45
msgid "online"
msgstr "Online"

#: module/database/FileDatabase.py:45
msgid "queued"
msgstr "em fila"

#: module/database/FileDatabase.py:45
msgid "skipped"
msgstr "ignorada"

#: module/database/FileDatabase.py:45
msgid "waiting"
msgstr "esperando"

#: module/database/FileDatabase.py:45
msgid "temp. offline"
msgstr "Temp. off-line"

#: module/database/FileDatabase.py:45
msgid "starting"
msgstr "iniciando"

#: module/database/FileDatabase.py:45
msgid "failed"
msgstr "falhou"

#: module/database/FileDatabase.py:45
msgid "aborted"
msgstr "abortada"

#: module/database/FileDatabase.py:45
msgid "decrypting"
msgstr "descriptografando"

#: module/database/FileDatabase.py:45
msgid "custom"
msgstr "personalizado"

#: module/database/FileDatabase.py:45
msgid "downloading"
msgstr "Transferindo"

#: module/database/FileDatabase.py:45
msgid "processing"
msgstr "processando"

#: module/database/FileDatabase.py:45
msgid "unknown"
msgstr "desconhecido"

#: module/database/FileDatabase.py:531 module/plugins/hooks/IRCInterface.py:74
#: module/plugins/hooks/XMPPInterface.py:83
#, python-format
msgid "Package finished: %s"
msgstr "Pacote finalizado: %s"

#: module/remote/ThriftBackend.py:39
msgid "Using SSL ThriftBackend"
msgstr ""

#: module/manager/RemoteManager.py:35
#, python-format
msgid "Remote backend error: %s"
msgstr "Erro de back-end remoto: %s"

#: module/manager/RemoteManager.py:82
#, python-format
msgid "Starting %(name)s: %(addr)s:%(port)s"
msgstr "Iniciando %(name)s: %(addr)s:%(port)s"

#: module/manager/RemoteManager.py:84
#, python-format
msgid "Failed loading backend %(name)s | %(error)s"
msgstr "Falha ao carregar back-end %(name)s | %(error)s"

#: module/web/json_app.py:57
#, python-format
msgid "waiting %s"
msgstr ""

#: module/web/ServerThread.py:35
msgid "SSL certificates not found."
msgstr "Certificado SSL não encontrado."

#: module/web/ServerThread.py:39
#, python-format
msgid "Sorry, we dropped support for starting %s directly within pyLoad"
msgstr ""

#: module/web/ServerThread.py:40
msgid "You can use the threaded server which offers good performance and ssl,"
msgstr ""

#: module/web/ServerThread.py:41
#, python-format
msgid "of course you can still use your existing %s with pyLoads fastcgi server"
msgstr ""

#: module/web/ServerThread.py:42
msgid "sample configs are located in the module/web/servers directory"
msgstr ""

#: module/web/ServerThread.py:49
#, python-format
msgid "Can't use %(server)s, python-flup is not installed!"
msgstr ""

#: module/web/ServerThread.py:56
#, python-format
msgid "Error importing lightweight server: %s"
msgstr ""

#: module/web/ServerThread.py:57
msgid "You need to download and compile bjoern, https://github.com/jonashaag/bjoern"
msgstr ""

#: module/web/ServerThread.py:58
msgid "Copy the boern.so to module/lib folder or use setup.py install"
msgstr ""

#: module/web/ServerThread.py:59
msgid "Of course you need to be familiar with linux and know how to compile software"
msgstr ""

#: module/web/ServerThread.py:63
msgid "Server set to threaded, due to known performance problems on windows."
msgstr ""

#: module/web/ServerThread.py:80 module/web/ServerThread.py:103
msgid "This server offers no SSL, please consider using threaded instead"
msgstr "Este servidor não oferece SSL, por favor, considere usar HTTP{?} em vez disso"

#: module/web/ServerThread.py:82
#, python-format
msgid "Starting builtin webserver: %(host)s:%(port)d"
msgstr ""

#: module/web/ServerThread.py:87
#, python-format
msgid "Starting threaded SSL webserver: %(host)s:%(port)d"
msgstr ""

#: module/web/ServerThread.py:91
#, python-format
msgid "Starting threaded webserver: %(host)s:%(port)d"
msgstr ""

#: module/web/ServerThread.py:97
#, python-format
msgid "Starting fastcgi server: %(host)s:%(port)d"
msgstr ""

#: module/web/ServerThread.py:105
#, python-format
msgid "Starting lightweight webserver (bjoern): %(host)s:%(port)d"
msgstr ""

#: module/web/pyload_app.py:125
msgid "You dont have permission to access this page."
msgstr ""

#: module/web/pyload_app.py:193
msgid "Download directory not found."
msgstr ""

#: module/web/pyload_app.py:260 module/web/pyload_app.py:267
msgid "unlimited"
msgstr "ilimitado"

#: module/web/pyload_app.py:262 module/web/pyload_app.py:269
msgid "not available"
msgstr ""

#: module/web/pyload_app.py:508
msgid "Run pyload.py -s to access the setup."
msgstr ""

#: module/network/HTTPDownload.py:245
#, python-format
msgid "Download chunks failed, fallback to single connection | %s"
msgstr "pedaços do Download falharam, retornar para conexão simples |%s"

#: module/PluginThread.py:183
#, python-format
msgid "Download starts: %s"
msgstr "Inicio do Download: %s"

#: module/PluginThread.py:189
#, python-format
msgid "Download finished: %s"
msgstr "Termino do Download: %s"

#: module/PluginThread.py:194 module/PluginThread.py:365
#, python-format
msgid "Plugin %s is missing a function."
msgstr "Plugin %s está sem uma função."

#: module/PluginThread.py:202 module/PluginThread.py:265
#: module/PluginThread.py:382
#, python-format
msgid "Download aborted: %s"
msgstr "Download abortado: %s"

#: module/PluginThread.py:222
#, python-format
msgid "Download restarted: %(name)s | %(msg)s"
msgstr "Download reiniciado: %(name)s | %(msg)s"

#: module/PluginThread.py:231 module/PluginThread.py:373
#, python-format
msgid "Download is offline: %s"
msgstr "Download está offline: %s"

#: module/PluginThread.py:234
#, python-format
msgid "Download is temporary offline: %s"
msgstr "Download esta temporariamente offline: %s"

#: module/PluginThread.py:237 module/PluginThread.py:304
#, python-format
msgid "Download failed: %(name)s | %(msg)s"
msgstr "Download falhou: %(name)s | %(msg)s"

#: module/PluginThread.py:254
msgid "Couldn't connect to host or connection reset, waiting 1 minute and retry."
msgstr "Impossível conectar com o host ou a conexão receptou, tentar novamente em 1 minuto."

#: module/PluginThread.py:290
#, python-format
msgid "Download skipped: %(name)s due to %(plugin)s"
msgstr "Download pulado: %(name)s pois %(plugin)s"

#: module/PluginThread.py:361
#, python-format
msgid "Decrypting starts: %s"
msgstr ""

#: module/PluginThread.py:376 module/PluginThread.py:394
#, python-format
msgid "Decrypting failed: %(name)s | %(msg)s"
msgstr ""

#: module/PluginThread.py:388
#, python-format
msgid "Retrying %s"
msgstr ""

#: module/PluginThread.py:635
#, python-format
msgid "Info Fetching for %(name)s failed | %(err)s"
msgstr "Busca de informações para %(name)s falhou|%(err)s"

#: module/manager/HookManager.py:90 module/plugins/Hook.py:102
#, python-format
msgid "Error executing hooks: %s"
msgstr ""

#: module/manager/HookManager.py:140
#, python-format
msgid "Failed activating %(name)s"
msgstr "Falha de ativação %(name)s"

#: module/manager/HookManager.py:144
#, python-format
msgid "Activated plugins: %s"
msgstr ""

#: module/manager/HookManager.py:145
#, python-format
msgid "Deactivate plugins: %s"
msgstr ""

#: module/manager/ThreadManager.py:137
#, python-format
msgid "Reconnect Failed: %s"
msgstr "Reconectar Falhou: %s"

#: module/manager/ThreadManager.py:176
msgid "Reconnect script not found!"
msgstr "Script de reconexão não encontrado!"

#: module/manager/ThreadManager.py:182
msgid "Starting reconnect"
msgstr "Iniciando reconexão"

#: module/manager/ThreadManager.py:196
msgid "Failed executing reconnect script!"
msgstr "Falha ao executar script de reconexão!"

#: module/manager/ThreadManager.py:208
#, python-format
msgid "Reconnected, new IP: %s"
msgstr "Reconectado, novo IP: %s"

#: module/manager/ThreadManager.py:288
msgid "Not enough space left on device"
msgstr "Espaço insuficiente no dispositivo"

#: module/plugins/Account.py:85 module/plugins/Account.py:91
#, python-format
msgid "Could not login with account %(user)s | %(msg)s"
msgstr "Não pode ligar com a conta %(user)s | %(msg)s"

#: module/plugins/Account.py:86
msgid "Wrong Password"
msgstr "Senha incorreta"

#: module/plugins/Account.py:240
#, python-format
msgid "Your Time %s has wrong format, use: 1:22-3:44"
msgstr ""

#: module/plugins/Account.py:266
#, python-format
msgid "Account %s has not enough traffic, checking again in 30min"
msgstr "A conta %s não tem tráfego suficiente, checando novamente em 30 min"

#: module/plugins/Account.py:273
#, python-format
msgid "Account %s is expired, checking again in 1h"
msgstr "A conta %s expirou, checando novamente em 1h"

#: module/plugins/crypter/SerienjunkiesOrg.py:128
msgid "Downloadlimit reached"
msgstr "Limite de Download alcançado"

#: module/manager/PluginManager.py:153
#, python-format
msgid "%s has a invalid pattern."
msgstr ""

#: module/manager/PluginManager.py:272
#, python-format
msgid "Error importing %(name)s: %(msg)s"
msgstr "Erro ao importar %(name)s: %(msg)s"

#: module/plugins/internal/MultiHoster.py:133
msgid "No Hoster loaded"
msgstr "Nenhum Hoster carregado"

#: module/plugins/accounts/BitshareCom.py:37
msgid "Activate direct Download in your Bitshare Account"
msgstr "Ativar Download direto em sua conta Bitshare"

#: module/plugins/container/LinkList.py:65
msgid "LinkList could not be cleared."
msgstr ""

#: module/manager/AccountManager.py:88
msgid "Account settings deleted, due to new config format."
msgstr ""

#: module/plugins/hoster/BasePlugin.py:65
msgid "Authorization required (username:password)"
msgstr "Autorização necessaria (nome de usuario: senha)"

#: module/plugins/hoster/SimplydebridCom.py:25
#: module/plugins/hoster/RealdebridCom.py:41
#: module/plugins/hoster/FreeWayMe.py:38 module/plugins/hoster/ZeveraCom.py:22
#: module/plugins/hoster/UnrestrictLi.py:53
#: module/plugins/hoster/Premium4Me.py:28 module/plugins/hoster/FastixRu.py:36
#: module/plugins/hoster/AlldebridCom.py:38
#: module/plugins/hoster/DebridItaliaCom.py:40
#: module/plugins/hoster/RPNetBiz.py:26
#: module/plugins/hoster/MultiDebridCom.py:41
#: module/plugins/hoster/ReloadCc.py:24 module/plugins/hoster/RehostTo.py:26
#: module/plugins/hoster/PremiumizeMe.py:22
#: module/plugins/hooks/RPNetBiz.py:43
#, python-format
msgid "Please enter your %s account or deactivate this plugin"
msgstr "Por favor entre sua %s conta ou desative este plugin"

#: module/plugins/hoster/FilesMailRu.py:99
#, python-format
msgid "There was HTML Code in the Downloaded File (%s)...redirect error? The Download will be restarted."
msgstr "Havia código HTML no arquivo baixado (%s)...erro de redirecionamento? O Download vai ser reiniciado."

#: module/plugins/hoster/NetloadIn.py:146
#: module/plugins/hoster/NetloadIn.py:170
msgid "File temporarily not available"
msgstr "Arquivo temporariamente indisponível"

#: module/plugins/hoster/NetloadIn.py:183
#, python-format
msgid "Netload: waiting between downloads %d s."
msgstr "Netload: esperar entre os Downloads %d s."

#: module/plugins/hoster/NetloadIn.py:214
#, python-format
msgid "Netload: waiting for captcha %d s."
msgstr "Netload: esperando por capacha %d s."

#: module/plugins/hoster/NetloadIn.py:252
msgid "Downloaded File was empty"
msgstr "Arquivo baixado estava vazio"

#: module/plugins/hoster/UploadedTo.py:129
msgid "API key invalid"
msgstr "Chave de API inválida"

#: module/plugins/hoster/UploadedTo.py:153
#, python-format
msgid "%s: Not enough traffic left"
msgstr "%s: Tráfego restante insuficiente"

#: module/plugins/hoster/UploadedTo.py:156
msgid "Traffic exceeded"
msgstr "Tráfego excedido"

#: module/plugins/hoster/RapidshareCom.py:100
msgid "Rapidshare: Traffic Share (direct download)"
msgstr "Rapidshare: Compartilhamento de tráfego (Download direto)"

#: module/plugins/hoster/RapidshareCom.py:127
#: module/plugins/hoster/RapidshareCom.py:194
msgid "Already downloading from this ip address, waiting 60 seconds"
msgstr "Ja está baixando deste endereço de ip, espere 60 segundos"

#: module/plugins/hoster/RapidshareCom.py:131
msgid "Invalid Auth Code, download will be restarted"
msgstr "Código de autenticação invalido, Download vai ser reiniciado"

#: module/plugins/hoster/RapidshareCom.py:199
msgid "RapidShareCom: No free slots"
msgstr "RapidShareCom: Sem slots vazios"

#: module/plugins/hoster/RapidshareCom.py:202
msgid "You need a premium account for this file"
msgstr "Você precisa de uma conta premium para este arquivo"

#: module/plugins/hoster/RapidshareCom.py:204
msgid "Filename reported invalid"
msgstr "Nome do arquivo relatado como invalido"

#: module/plugins/hoster/FileserveCom.py:99
msgid "Parallel download error, now waiting 60s."
msgstr "Erro de Download paralelo, esperar 60 segundos."

#: module/plugins/hoster/FileserveCom.py:215
msgid "Not logged in."
msgstr "Não está logado."

#: module/plugins/hoster/MegaNz.py:56
msgid "Decryption failed"
msgstr "Descriptografia falhou"

#: module/plugins/hoster/MegaNz.py:106
msgid "No file key provided in the URL"
msgstr "Nenhum arquivo chave fornecido na URL"

#: module/plugins/hoster/MegaNz.py:118
msgid "Error code:"
msgstr "Codigo do erro:"

#: module/plugins/Container.py:68
msgid "File not exists."
msgstr ""

#: module/plugins/hooks/UpdateManager.py:74
msgid "*** Plugins have been updated, please restart pyLoad ***"
msgstr "*** Plugins foram atualizados, por favor reinicie o pyLoad ***"

#: module/plugins/hooks/UpdateManager.py:76
msgid "Plugins updated and reloaded"
msgstr "Plugins atualizados e recarregados"

#: module/plugins/hooks/UpdateManager.py:79
msgid "No plugin updates available"
msgstr "Nenhuma atualização de plugin disponível"

#: module/plugins/hooks/UpdateManager.py:96
msgid "No Updates for pyLoad"
msgstr "Nenhuma atualização para o pyLoad"

#: module/plugins/hooks/UpdateManager.py:100
#, python-format
msgid "***  New pyLoad Version %s available  ***"
msgstr "* * * Nova versão %s do pyLoad disponível * * *"

#: module/plugins/hooks/UpdateManager.py:101
msgid "***  Get it here: http://pyload.org/download  ***"
msgstr "* * * faça o Download em : http://pyload.org/download * * *"

#: module/plugins/hooks/UpdateManager.py:104
msgid "Not able to connect server for updates"
msgstr "Impossível conectar com o servidor de atualizações"

#: module/plugins/hooks/UpdateManager.py:148
#, python-format
msgid "New version of %(type)s|%(name)s : %(version).2f"
msgstr "Nova versão de %(type)s|%(name)s : %(version).2f"

#: module/plugins/hooks/UpdateManager.py:157
#: module/plugins/hooks/UpdateManager.py:162
#, python-format
msgid "Error when updating %s"
msgstr "Erro ao atualizar %s"

#: module/plugins/hooks/UpdateManager.py:162
msgid "Version mismatch"
msgstr "Incompatibilidade de versão"

#: module/plugins/hooks/IRCInterface.py:82
#, python-format
msgid "Download finished: %(name)s @ %(plugin)s "
msgstr "Download concluído: %(name)s @ %(plugin)s "

#: module/plugins/hooks/IRCInterface.py:95
#, python-format
msgid "New Captcha Request: %s"
msgstr "Nova solicitação de Captcha: %s"

#: module/plugins/hooks/IRCInterface.py:96
#, python-format
msgid "Answer with 'c %s text on the captcha'"
msgstr "Responder com 'c %s o texto no captcha'"

#: module/plugins/hooks/Premium4Me.py:29
msgid "Please add your premium.to account first and restart pyLoad"
msgstr ""

#: module/plugins/hooks/HotFolder.py:82
#, python-format
msgid "Added %s from HotFolder"
msgstr "Adicionado %s de HotFolder"

#: module/plugins/hooks/ExtractArchive.py:95
#, python-format
msgid "No %s installed"
msgstr "Sem %s instalado"

#: module/plugins/hooks/ExtractArchive.py:97
#: module/plugins/hooks/ExtractArchive.py:102
#, python-format
msgid "Could not activate %s"
msgstr "Não foi possível activar o %s"

#: module/plugins/hooks/ExtractArchive.py:107
msgid "Activated"
msgstr "Ativado"

#: module/plugins/hooks/ExtractArchive.py:109
msgid "No Extract plugins activated"
msgstr "Não ha plugins de extração ativos"

#: module/plugins/hooks/ExtractArchive.py:121
#, python-format
msgid "Package %s queued for later extracting"
msgstr "Pacote %s enfileirados para extração posterior"

#: module/plugins/hooks/ExtractArchive.py:144
#, python-format
msgid "Check package %s"
msgstr "Verificar pacote %s"

#: module/plugins/hooks/ExtractArchive.py:185
#, python-format
msgid "Extract to %s"
msgstr "Extrair para %s"

#: module/plugins/hooks/ExtractArchive.py:200
msgid "No files found to extract"
msgstr "Arquivos não encontrados para extrair"

#: module/plugins/hooks/ExtractArchive.py:207
msgid "extracting"
msgstr "extraindo"

#: module/plugins/hooks/ExtractArchive.py:218
msgid "Password protected"
msgstr "Protegido por senha"

#: module/plugins/hooks/ExtractArchive.py:239
msgid "Wrong password"
msgstr "Senha incorreta"

#: module/plugins/hooks/ExtractArchive.py:247
#, python-format
msgid "Deleting %s files"
msgstr "Excluindo %s arquivos"

#: module/plugins/hooks/ExtractArchive.py:254
msgid "Extracting finished"
msgstr "Extração terminada"

#: module/plugins/hooks/ExtractArchive.py:260
msgid "Archive Error"
msgstr "Erro de arquivo"

#: module/plugins/hooks/ExtractArchive.py:262
msgid "CRC Mismatch"
msgstr "Incompatibilidade de CRC"

#: module/plugins/hooks/ExtractArchive.py:266
msgid "Unknown Error"
msgstr "Erro desconhecido"

#: module/plugins/hooks/ExtractArchive.py:318
msgid "Setting User and Group failed"
msgstr "Configuração de usuário e grupo falhou"

#: module/plugins/hooks/ClickAndLoad.py:75
msgid "Click'N'Load: Port 9666 already in use"
msgstr "Click'n'Load: porta 9666 já está em uso"

#: module/plugins/hooks/CaptchaTrader.py:69
#: module/plugins/hooks/Captcha9kw.py:59
#: module/plugins/hooks/ExpertDecoders.py:50
#, python-format
msgid "%s credits left"
msgstr "%s créditos sobrando"

#: module/plugins/hooks/CaptchaTrader.py:117
msgid "Could not send response."
msgstr "Não pode enviar resposta."

#: module/plugins/hooks/CaptchaTrader.py:135
msgid "Your CaptchaTrader Account has not enough credits"
msgstr "Sua conta CaptchaTrader não tem créditos suficientes"

#: module/plugins/hooks/LinkdecrypterCom.py:43
msgid "Crypter list not found"
msgstr "Lista do Crypter não encontrada"

#: module/plugins/hooks/LinkdecrypterCom.py:57
msgid "Crypter list is empty"
msgstr "Lista do Crypter vazia"

#: module/plugins/hooks/XMPPInterface.py:91
#, python-format
msgid "Download finished: %(name)s @ %(plugin)s"
msgstr "Download terminado: %(name)s @ %(plugin)s"

#: module/plugins/hooks/Captcha9kw.py:93
#, python-format
msgid "New CaptchaID from upload: %s : %s"
msgstr "Novo CaptchaID do upload: %s : %s"

#: module/plugins/hooks/Captcha9kw.py:129
msgid "Your Captcha 9kw.eu Account has not enough credits"
msgstr "Sua conta 9kw.eu não tem créditos suficientes"

#: module/plugins/hooks/ExternalScripts.py:54
#, python-format
msgid "Installed scripts for %s: "
msgstr "scripts instalados para %s: "

#: module/plugins/hooks/ExternalScripts.py:69
msgid "Script not executable:"
msgstr "Scrip não executável:"

#: module/plugins/hooks/ExternalScripts.py:80
#, python-format
msgid "Error in %(script)s: %(error)s"
msgstr "Erro em %(script)s: %(error)s"

#: module/plugins/hooks/ExpertDecoders.py:95
msgid "Your ExpertDecoders Account has not enough credits"
msgstr "Sua conta ExpertDecoders não tem créditos suficientes"

#: module/plugins/hooks/RehostTo.py:32
msgid "Please add your rehost.to account first and restart pyLoad"
msgstr "Por favo adicione sua conta rehost.to antes de reiniciar o pyLoad"

#: module/plugins/hooks/PremiumizeMe.py:48
msgid "Please add a valid premiumize.me account first and restart pyLoad."
msgstr ""

#: module/plugins/hooks/CaptchaBrotherhood.py:69
#, python-format
msgid "%d credits left"
msgstr "%d créditos sobrando"

#: module/plugins/Base.py:389
msgid "Pil and tesseract not installed and no Client connected for captcha decrypting"
msgstr "Pil e tesseract não estão instalados e nenhum cliente está conectado para reconhecimento de captcha"

#: module/plugins/Base.py:393
msgid "No captcha result obtained in appropiate time by any of the plugins."
msgstr ""

#: module/plugins/Base.py:498 module/plugins/Base.py:532
#, python-format
msgid "Setting User and Group failed: %s"
msgstr "Configuração de usuário e grupo falhou: %s"

#: module/manager/CaptchaManager.py:78
msgid "No Client connected for captcha decrypting"
msgstr ""

#: module/Api.py:330
#, python-format
msgid "Added package %(name)s containing %(count)d links"
msgstr ""

#: module/Api.py:593
#, python-format
msgid "Added %(count)d links to package #%(package)d "
msgstr ""

#: module/utils/JsEngine.py:156
msgid "No js engine detected, please install either Spidermonkey, ossp-js, pyv8 or rhino"
msgstr ""

