msgid ""
msgstr "Project-Id-Version: pyload\n"
"Report-Msgid-Bugs-To: 'bugs@pyload.org'\n"
"POT-Creation-Date: 2014-04-08 15:01+0200\n"
"PO-Revision-Date: 2014-04-09 05:38-0400\n"
"Last-Translator: pyloadTeam <team@pyload.org>\n"
"Language-Team: Chinese Traditional\n"
"Language: zh_TW\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: crowdin.net\n"

#: module/Core.py:182
msgid "Received Quit signal"
msgstr "收到退出訊號"

#: module/Core.py:303
#, python-format
msgid "pyLoad already running with pid %s"
msgstr "pyLoad已經在執行，pid %s"

#: module/Core.py:317
#, python-format
msgid "Failed changing group: %s"
msgstr "無法改變群組： %s"

#: module/Core.py:327
#, python-format
msgid "Failed changing user: %s"
msgstr "無法改變使用者： %s"

#: module/Core.py:329
msgid "folder for logs"
msgstr "LOG文件夹"

#: module/Core.py:340
msgid "Starting"
msgstr "開始"

#: module/Core.py:341
#, python-format
msgid "Using home directory: %s"
msgstr "使用家目錄： %s"

#: module/Core.py:350
msgid "pycrypto to decode container files"
msgstr "使用pycrypto解密文件"

#: module/Core.py:353
msgid "folder for temporary files"
msgstr "临时文件夹"

#: module/Core.py:358
msgid "folder for downloads"
msgstr "下载文件夹"

#: module/Core.py:361
msgid "OpenSSL for secure connection"
msgstr "使用OpenSSL安全登陆"

#: module/Core.py:365
msgid "Moving old user config to DB"
msgstr "将旧用户设定移入数据库"

#: module/Core.py:368
msgid "Please check your logindata with ./pyload.py -u"
msgstr "请执行./pyload.py -u 来确认你的logindata"

#: module/Core.py:371
msgid "All links removed"
msgstr "刪除所有連結"

#: module/Core.py:402
#, python-format
msgid "Downloadtime: %s"
msgstr "下载时间：%s"

#: module/Core.py:412
#, python-format
msgid "Free space: %s"
msgstr "剩餘空間： %s"

#: module/Core.py:432
msgid "Activating Accounts..."
msgstr "啟動帳戶..."

#: module/Core.py:438
msgid "Activating Plugins..."
msgstr "激活插件中..."

#: module/Core.py:441
msgid "pyLoad is up and running"
msgstr "pyLoad已是最新的狀態"

#: module/Core.py:460
msgid "restarting pyLoad"
msgstr "重新啟動pyLoad"

#: module/Core.py:464
msgid "pyLoad quits"
msgstr "離開pyLoad"

#: module/Core.py:521
#, python-format
msgid "Install %s"
msgstr "安装 %s"

#: module/Core.py:557
#, python-format
msgid "could not find %(desc)s: %(name)s"
msgstr "无法找到%(desc)s: %(name)s"

#: module/Core.py:559
#, python-format
msgid "could not create %(desc)s: %(name)s"
msgstr "无法创建%(desc)s: %(name)s"

#: module/Core.py:580
msgid "shutting down..."
msgstr "關閉..."

#: module/Core.py:597
msgid "error while shutting down"
msgstr "關閉時出現錯誤"

#: module/Core.py:661
msgid "killed pyLoad from Terminal"
msgstr ""

#: module/database/DatabaseBackend.py:174
msgid "Filedatabase was deleted due to incompatible version."
msgstr ""

#: module/database/DatabaseBackend.py:189
msgid "Filedatabase could NOT be converted."
msgstr ""

#: module/database/DatabaseBackend.py:198
msgid "Database was converted from v2 to v3."
msgstr ""

#: module/database/DatabaseBackend.py:206
msgid "Database was converted from v3 to v4."
msgstr ""

#: module/database/DatabaseBackend.py:252
msgid "Converting old Django DB"
msgstr ""

#: module/database/FileDatabase.py:45
msgid "finished"
msgstr "已完成"

#: module/database/FileDatabase.py:45
msgid "offline"
msgstr "離線"

#: module/database/FileDatabase.py:45
msgid "online"
msgstr "線上"

#: module/database/FileDatabase.py:45
msgid "queued"
msgstr "佇列"

#: module/database/FileDatabase.py:45
msgid "skipped"
msgstr "跳過"

#: module/database/FileDatabase.py:45
msgid "waiting"
msgstr "等待中"

#: module/database/FileDatabase.py:45
msgid "temp. offline"
msgstr "暫時離線"

#: module/database/FileDatabase.py:45
msgid "starting"
msgstr "開始"

#: module/database/FileDatabase.py:45
msgid "failed"
msgstr "失敗"

#: module/database/FileDatabase.py:45
msgid "aborted"
msgstr "中止"

#: module/database/FileDatabase.py:45
msgid "decrypting"
msgstr "解析"

#: module/database/FileDatabase.py:45
msgid "custom"
msgstr "自訂"

#: module/database/FileDatabase.py:45
msgid "downloading"
msgstr "下載中"

#: module/database/FileDatabase.py:45
msgid "processing"
msgstr "處理中"

#: module/database/FileDatabase.py:45
msgid "unknown"
msgstr "未知"

#: module/database/FileDatabase.py:531 module/plugins/addon/IRCInterface.py:74
#: module/plugins/addon/XMPPInterface.py:83
#, python-format
msgid "Package finished: %s"
msgstr "套件已完成： %s"

#: module/remote/ThriftBackend.py:39
msgid "Using SSL ThriftBackend"
msgstr ""

#: module/manager/RemoteManager.py:35
#, python-format
msgid "Remote backend error: %s"
msgstr "遠端錯誤： %s"

#: module/manager/RemoteManager.py:82
#, python-format
msgid "Starting %(name)s: %(addr)s:%(port)s"
msgstr "%(name)s ：%(addr)s:%(port)s 啟動中"

#: module/manager/RemoteManager.py:84
#, python-format
msgid "Failed loading backend %(name)s | %(error)s"
msgstr "無法載入 %(name)s： %(error)s"

#: module/web/json_app.py:57
#, python-format
msgid "waiting %s"
msgstr ""

#: module/thread/ServerThread.py:35
msgid "SSL certificates not found."
msgstr "沒有找到SSL憑證"

#: module/thread/ServerThread.py:39
#, python-format
msgid "Sorry, we dropped support for starting %s directly within pyLoad"
msgstr ""

#: module/thread/ServerThread.py:40
msgid "You can use the threaded server which offers good performance and ssl,"
msgstr ""

#: module/thread/ServerThread.py:41
#, python-format
msgid "of course you can still use your existing %s with pyLoads fastcgi server"
msgstr ""

#: module/thread/ServerThread.py:42
msgid "sample configs are located in the module/web/servers directory"
msgstr ""

#: module/thread/ServerThread.py:49
#, python-format
msgid "Can't use %(server)s, python-flup is not installed!"
msgstr ""

#: module/thread/ServerThread.py:56
#, python-format
msgid "Error importing lightweight server: %s"
msgstr ""

#: module/thread/ServerThread.py:57
msgid "You need to download and compile bjoern, https://github.com/jonashaag/bjoern"
msgstr ""

#: module/thread/ServerThread.py:58
msgid "Copy the boern.so to module/lib folder or use Setup.py install"
msgstr ""

#: module/thread/ServerThread.py:59
msgid "Of course you need to be familiar with linux and know how to compile software"
msgstr ""

#: module/thread/ServerThread.py:63
msgid "Server set to threaded, due to known performance problems on windows."
msgstr ""

#: module/thread/ServerThread.py:80 module/thread/ServerThread.py:103
msgid "This server offers no SSL, please consider using threaded instead"
msgstr "目前的服務器不支援SSL，請將伺服器模式改為Threaded"

#: module/thread/ServerThread.py:82
#, python-format
msgid "Starting builtin webserver: %(host)s:%(port)d"
msgstr ""

#: module/thread/ServerThread.py:87
#, python-format
msgid "Starting threaded SSL webserver: %(host)s:%(port)d"
msgstr ""

#: module/thread/ServerThread.py:91
#, python-format
msgid "Starting threaded webserver: %(host)s:%(port)d"
msgstr ""

#: module/thread/ServerThread.py:97
#, python-format
msgid "Starting fastcgi server: %(host)s:%(port)d"
msgstr ""

#: module/thread/ServerThread.py:105
#, python-format
msgid "Starting lightweight webserver (bjoern): %(host)s:%(port)d"
msgstr ""

#: module/web/pyload_app.py:125
msgid "You dont have permission to access this page."
msgstr ""

#: module/web/pyload_app.py:193
msgid "Download directory not found."
msgstr ""

#: module/web/pyload_app.py:260 module/web/pyload_app.py:267
msgid "unlimited"
msgstr "無限制"

#: module/web/pyload_app.py:262 module/web/pyload_app.py:269
msgid "not available"
msgstr ""

#: module/web/pyload_app.py:508
msgid "Run pyload.py -s to access the setup."
msgstr ""

#: module/network/HTTPDownload.py:245
#, python-format
msgid "Download chunks failed, fallback to single connection | %s"
msgstr "分區下載失敗，採用單一連接下載｜%s"

#: module/thread/PluginThread.py:183
#, python-format
msgid "Download starts: %s"
msgstr "開始下載 %s"

#: module/thread/PluginThread.py:189
#, python-format
msgid "Download finished: %s"
msgstr "%s 下載完成"

#: module/thread/PluginThread.py:194 module/thread/PluginThread.py:365
#, python-format
msgid "Plugin %s is missing a function."
msgstr "%s 模組缺少相關功能"

#: module/thread/PluginThread.py:202 module/thread/PluginThread.py:265
#: module/thread/PluginThread.py:382
#, python-format
msgid "Download aborted: %s"
msgstr "取消下載 %s"

#: module/thread/PluginThread.py:222
#, python-format
msgid "Download restarted: %(name)s | %(msg)s"
msgstr "重新下載%(name)s ｜%(msg)s"

#: module/thread/PluginThread.py:231 module/thread/PluginThread.py:373
#, python-format
msgid "Download is offline: %s"
msgstr "下載任務斷線：%s"

#: module/thread/PluginThread.py:234
#, python-format
msgid "Download is temporary offline: %s"
msgstr "下載任務暫時斷線：%s"

#: module/thread/PluginThread.py:237 module/thread/PluginThread.py:304
#, python-format
msgid "Download failed: %(name)s | %(msg)s"
msgstr "%(name)s 下載失敗｜%(msg)s"

#: module/thread/PluginThread.py:254
msgid "Couldn't connect to host or connection reset, waiting 1 minute and retry."
msgstr "無法連線至host，一分鐘後重試"

#: module/thread/PluginThread.py:290
#, python-format
msgid "Download skipped: %(name)s due to %(plugin)s"
msgstr "%(name)s 取消下載，由於 %(plugin)s"

#: module/thread/PluginThread.py:361
#, python-format
msgid "Decrypting starts: %s"
msgstr ""

#: module/thread/PluginThread.py:376 module/thread/PluginThread.py:394
#, python-format
msgid "Decrypting failed: %(name)s | %(msg)s"
msgstr ""

#: module/thread/PluginThread.py:388
#, python-format
msgid "Retrying %s"
msgstr ""

#: module/thread/PluginThread.py:635
#, python-format
msgid "Info Fetching for %(name)s failed | %(err)s"
msgstr "取得 %(name)s的錯誤資訊|%(err)s"

#: module/manager/AddonManager.py:90 module/plugins/Addon.py:102
#, python-format
msgid "Error executing addon: %s"
msgstr ""

#: module/manager/AddonManager.py:140
#, python-format
msgid "Failed activating %(name)s"
msgstr "啟用 %(name)s 時發生錯誤"

#: module/manager/AddonManager.py:144
#, python-format
msgid "Activated plugins: %s"
msgstr ""

#: module/manager/AddonManager.py:145
#, python-format
msgid "Deactivate plugins: %s"
msgstr ""

#: module/manager/ThreadManager.py:137
#, python-format
msgid "Reconnect Failed: %s"
msgstr "重新連接失敗: %s"

#: module/manager/ThreadManager.py:176
msgid "Reconnect script not found!"
msgstr "重新連接腳本未找到 ！"

#: module/manager/ThreadManager.py:182
msgid "Starting reconnect"
msgstr "開始重試"

#: module/manager/ThreadManager.py:196
msgid "Failed executing reconnect script!"
msgstr "執行重試腳本失敗"

#: module/manager/ThreadManager.py:208
#, python-format
msgid "Reconnected, new IP: %s"
msgstr "使用新IP: %s 重試"

#: module/manager/ThreadManager.py:288
msgid "Not enough space left on device"
msgstr "儲存空間不足"

#: module/plugins/Account.py:85 module/plugins/Account.py:91
#, python-format
msgid "Could not login with account %(user)s | %(msg)s"
msgstr "無法登入%(user)s ｜%(msg)s"

#: module/plugins/Account.py:86
msgid "Wrong Password"
msgstr "密碼錯誤"

#: module/plugins/Account.py:240
#, python-format
msgid "Your Time %s has wrong format, use: 1:22-3:44"
msgstr ""

#: module/plugins/Account.py:266
#, python-format
msgid "Account %s has not enough traffic, checking again in 30min"
msgstr "帳戶 %s 流量用鑿，30分鐘後重新檢查"

#: module/plugins/Account.py:273
#, python-format
msgid "Account %s is expired, checking again in 1h"
msgstr "帳戶 %s 已過期，一小時後重試"

#: module/plugins/crypter/SerienjunkiesOrg.py:128
msgid "Downloadlimit reached"
msgstr "已達到下載流量上限"

#: module/manager/PluginManager.py:153
#, python-format
msgid "%s has a invalid pattern."
msgstr ""

#: module/manager/PluginManager.py:272
#, python-format
msgid "Error importing %(name)s: %(msg)s"
msgstr "發現錯誤 %(name)s: %(msg)s"

#: module/plugins/internal/MultiHoster.py:133
msgid "No Hoster loaded"
msgstr "找不到任何Hoster"

#: module/plugins/account/BitshareCom.py:37
msgid "Activate direct Download in your Bitshare Account"
msgstr "從您的Bitshare帳號中直接下載"

#: module/plugins/container/LinkList.py:65
msgid "LinkList could not be cleared."
msgstr ""

#: module/manager/AccountManager.py:88
msgid "Account settings deleted, due to new config format."
msgstr ""

#: module/plugins/hoster/BasePlugin.py:65
msgid "Authorization required (username:password)"
msgstr "需要認證（帳號：密碼）"

#: module/plugins/hoster/SimplydebridCom.py:25
#: module/plugins/hoster/RealdebridCom.py:41
#: module/plugins/hoster/FreeWayMe.py:38 module/plugins/hoster/ZeveraCom.py:22
#: module/plugins/hoster/UnrestrictLi.py:53
#: module/plugins/hoster/Premium4Me.py:28 module/plugins/hoster/FastixRu.py:36
#: module/plugins/hoster/AlldebridCom.py:38
#: module/plugins/hoster/DebridItaliaCom.py:40
#: module/plugins/hoster/RPNetBiz.py:26
#: module/plugins/hoster/MultiDebridCom.py:41
#: module/plugins/hoster/ReloadCc.py:24 module/plugins/hoster/RehostTo.py:26
#: module/plugins/hoster/PremiumizeMe.py:22
#: module/plugins/addon/RPNetBiz.py:43
#, python-format
msgid "Please enter your %s account or deactivate this plugin"
msgstr "請輸入你的帳戶或是停用此模組"

#: module/plugins/hoster/FilesMailRu.py:99
#, python-format
msgid "There was HTML Code in the Downloaded File (%s)...redirect error? The Download will be restarted."
msgstr "下載檔案中包含HTML語法，解析錯誤嗎？準備重試"

#: module/plugins/hoster/NetloadIn.py:146
#: module/plugins/hoster/NetloadIn.py:170
msgid "File temporarily not available"
msgstr "檔案暫時無法下載"

#: module/plugins/hoster/NetloadIn.py:183
#, python-format
msgid "Netload: waiting between downloads %d s."
msgstr ""

#: module/plugins/hoster/NetloadIn.py:214
#, python-format
msgid "Netload: waiting for captcha %d s."
msgstr ""

#: module/plugins/hoster/NetloadIn.py:252
msgid "Downloaded File was empty"
msgstr "下載的檔案是空的"

#: module/plugins/hoster/UploadedTo.py:129
msgid "API key invalid"
msgstr "API金鑰無效"

#: module/plugins/hoster/UploadedTo.py:153
#, python-format
msgid "%s: Not enough traffic left"
msgstr "%s: 流量已用完"

#: module/plugins/hoster/UploadedTo.py:156
msgid "Traffic exceeded"
msgstr "超出流量限制"

#: module/plugins/hoster/RapidshareCom.py:100
msgid "Rapidshare: Traffic Share (direct download)"
msgstr ""

#: module/plugins/hoster/RapidshareCom.py:127
#: module/plugins/hoster/RapidshareCom.py:194
msgid "Already downloading from this ip address, waiting 60 seconds"
msgstr "此IP位址已在下載另一項目，請等待六十秒後重試"

#: module/plugins/hoster/RapidshareCom.py:131
msgid "Invalid Auth Code, download will be restarted"
msgstr "驗證失敗，任務即將重試"

#: module/plugins/hoster/RapidshareCom.py:199
msgid "RapidShareCom: No free slots"
msgstr ""

#: module/plugins/hoster/RapidshareCom.py:202
msgid "You need a premium account for this file"
msgstr "此檔案需要高級用戶才能下載"

#: module/plugins/hoster/RapidshareCom.py:204
msgid "Filename reported invalid"
msgstr "不正確的檔名"

#: module/plugins/hoster/FileserveCom.py:99
msgid "Parallel download error, now waiting 60s."
msgstr "同時下載錯誤，60秒後重試"

#: module/plugins/hoster/FileserveCom.py:215
msgid "Not logged in."
msgstr "未登入"

#: module/plugins/hoster/MegaNz.py:56
msgid "Decryption failed"
msgstr "解析失敗"

#: module/plugins/hoster/MegaNz.py:106
msgid "No file key provided in the URL"
msgstr "URL未提供金鑰"

#: module/plugins/hoster/MegaNz.py:118
msgid "Error code:"
msgstr "錯誤碼："

#: module/plugins/Container.py:68
msgid "File not exists."
msgstr ""

#: module/plugins/addon/UpdateManager.py:74
msgid "*** Plugins have been updated, please restart pyLoad ***"
msgstr "＊＊＊外掛已更新，請重新啟動pyLoad＊＊＊"

#: module/plugins/addon/UpdateManager.py:76
msgid "Plugins updated and reloaded"
msgstr "外掛已更新"

#: module/plugins/addon/UpdateManager.py:79
msgid "No plugin updates available"
msgstr "外掛沒有可用的更新"

#: module/plugins/addon/UpdateManager.py:96
msgid "No Updates for pyLoad"
msgstr "pyLoad沒有可用的更新"

#: module/plugins/addon/UpdateManager.py:100
#, python-format
msgid "***  New pyLoad Version %s available  ***"
msgstr "＊＊＊pyLoad有新版本%s可使用＊＊＊"

#: module/plugins/addon/UpdateManager.py:101
msgid "***  Get it here: http://pyload.org/download  ***"
msgstr "*** 請從此下載 http://pyload.org/download ***"

#: module/plugins/addon/UpdateManager.py:104
msgid "Not able to connect server for updates"
msgstr "無法連線至更新伺服器"

#: module/plugins/addon/UpdateManager.py:148
#, python-format
msgid "New version of %(type)s|%(name)s : %(version).2f"
msgstr "新版本 %(type)s|%(name)s : %(version).2f"

#: module/plugins/addon/UpdateManager.py:157
#: module/plugins/addon/UpdateManager.py:162
#, python-format
msgid "Error when updating %s"
msgstr "更新 %s 時發生錯誤"

#: module/plugins/addon/UpdateManager.py:162
msgid "Version mismatch"
msgstr "版本不合"

#: module/plugins/addon/IRCInterface.py:82
#, python-format
msgid "Download finished: %(name)s @ %(plugin)s "
msgstr "%(name)s @ %(plugin)s 已完成"

#: module/plugins/addon/IRCInterface.py:95
#, python-format
msgid "New Captcha Request: %s"
msgstr "驗證碼請求: %s"

#: module/plugins/addon/IRCInterface.py:96
#, python-format
msgid "Answer with 'c %s text on the captcha'"
msgstr "請輸入驗證碼上的文字 %s"

#: module/plugins/addon/Premium4Me.py:29
msgid "Please add your premium.to account first and restart pyLoad"
msgstr "請先添加premium.to帳戶並重新啟動pyLoad"

#: module/plugins/addon/HotFolder.py:82
#, python-format
msgid "Added %s from HotFolder"
msgstr "從HotFolder增加 %s"

#: module/plugins/addon/ExtractArchive.py:95
#, python-format
msgid "No %s installed"
msgstr "未安裝 %s"

#: module/plugins/addon/ExtractArchive.py:97
#: module/plugins/addon/ExtractArchive.py:102
#, python-format
msgid "Could not activate %s"
msgstr "無法啟用 %s"

#: module/plugins/addon/ExtractArchive.py:107
msgid "Activated"
msgstr "已啟用"

#: module/plugins/addon/ExtractArchive.py:109
msgid "No Extract plugins activated"
msgstr "解壓縮外掛未啟用"

#: module/plugins/addon/ExtractArchive.py:121
#, python-format
msgid "Package %s queued for later extracting"
msgstr "任務 %s 已排入解壓佇列"

#: module/plugins/addon/ExtractArchive.py:144
#, python-format
msgid "Check package %s"
msgstr "檢查下載任務 %s"

#: module/plugins/addon/ExtractArchive.py:185
#, python-format
msgid "Extract to %s"
msgstr "解壓縮至 %s"

#: module/plugins/addon/ExtractArchive.py:200
msgid "No files found to extract"
msgstr "無法找到壓縮檔"

#: module/plugins/addon/ExtractArchive.py:207
msgid "extracting"
msgstr "解壓縮中"

#: module/plugins/addon/ExtractArchive.py:218
msgid "Password protected"
msgstr "被加密的壓縮檔"

#: module/plugins/addon/ExtractArchive.py:239
msgid "Wrong password"
msgstr "密碼錯誤"

#: module/plugins/addon/ExtractArchive.py:247
#, python-format
msgid "Deleting %s files"
msgstr "刪除檔案 %s"

#: module/plugins/addon/ExtractArchive.py:254
msgid "Extracting finished"
msgstr "解壓縮完成"

#: module/plugins/addon/ExtractArchive.py:260
msgid "Archive Error"
msgstr "壓縮檔損毀"

#: module/plugins/addon/ExtractArchive.py:262
msgid "CRC Mismatch"
msgstr "CRC不正確"

#: module/plugins/addon/ExtractArchive.py:266
msgid "Unknown Error"
msgstr "未知錯誤"

#: module/plugins/addon/ExtractArchive.py:318
msgid "Setting User and Group failed"
msgstr "設定使用者及群組失敗"

#: module/plugins/addon/ClickAndLoad.py:75
msgid "Click'N'Load: Port 9666 already in use"
msgstr "Click'N'Load: 9666阜已被使用"

#: module/plugins/addon/CaptchaTrader.py:69
#: module/plugins/addon/Captcha9kw.py:59
#: module/plugins/addon/ExpertDecoders.py:50
#, python-format
msgid "%s credits left"
msgstr "額度剩餘 %s"

#: module/plugins/addon/CaptchaTrader.py:117
msgid "Could not send response."
msgstr "無法發送回應。"

#: module/plugins/addon/CaptchaTrader.py:135
msgid "Your CaptchaTrader Account has not enough credits"
msgstr "CaptchaTrader帳戶額度不足"

#: module/plugins/addon/LinkdecrypterCom.py:43
msgid "Crypter list not found"
msgstr "未找到Crypter清單"

#: module/plugins/addon/LinkdecrypterCom.py:57
msgid "Crypter list is empty"
msgstr "Crypter清單是空的"

#: module/plugins/addon/XMPPInterface.py:91
#, python-format
msgid "Download finished: %(name)s @ %(plugin)s"
msgstr "%(name)s @ %(plugin)s 完成"

#: module/plugins/addon/Captcha9kw.py:93
#, python-format
msgid "New CaptchaID from upload: %s : %s"
msgstr "上傳新的CaptchaID：%s:%s"

#: module/plugins/addon/Captcha9kw.py:129
msgid "Your Captcha 9kw.eu Account has not enough credits"
msgstr "9kw.eu帳戶額度不足"

#: module/plugins/addon/ExternalScripts.py:54
#, python-format
msgid "Installed scripts for %s: "
msgstr "%s 已安裝的腳本"

#: module/plugins/addon/ExternalScripts.py:69
msgid "Script not executable:"
msgstr "無法執行腳本"

#: module/plugins/addon/ExternalScripts.py:80
#, python-format
msgid "Error in %(script)s: %(error)s"
msgstr "%(script)s： %(error)s"

#: module/plugins/addon/ExpertDecoders.py:95
msgid "Your ExpertDecoders Account has not enough credits"
msgstr "ExpertDecoders帳戶額度不足"

#: module/plugins/addon/RehostTo.py:32
msgid "Please add your rehost.to account first and restart pyLoad"
msgstr "請先添加rehost.to帳戶並重新啟動pyLoad"

#: module/plugins/addon/PremiumizeMe.py:48
msgid "Please add a valid premiumize.me account first and restart pyLoad."
msgstr "請先設定premiumize.me帳戶並重新啟動pyLoad"

#: module/plugins/addon/CaptchaBrotherhood.py:69
#, python-format
msgid "%d credits left"
msgstr "額度剩下 %d"

#: module/plugins/Base.py:389
msgid "Pil and tesseract not installed and no Client connected for captcha decrypting"
msgstr "尚未安裝Pil及tesseract，尚未連接至需要解析的客戶端"

#: module/plugins/Base.py:393
msgid "No captcha result obtained in appropiate time by any of the plugins."
msgstr ""

#: module/plugins/Base.py:498 module/plugins/Base.py:532
#, python-format
msgid "Setting User and Group failed: %s"
msgstr "設置使用者和組失敗： %s"

#: module/manager/CaptchaManager.py:78
msgid "No Client connected for captcha decrypting"
msgstr ""

#: module/Api.py:330
#, python-format
msgid "Added package %(name)s containing %(count)d links"
msgstr ""

#: module/Api.py:593
#, python-format
msgid "Added %(count)d links to package #%(package)d "
msgstr ""

#: module/utils/JsEngine.py:156
msgid "No js engine detected, please install either Spidermonkey, ossp-js, pyv8 or rhino"
msgstr ""

